2024-08-13 14:32:20.534: Error occurred during sendPostRequestToDatadog in sendLogs:
2024-08-13 14:32:20.535: {"Op":"Post","URL":"https://http-intake.logs.datadoghq.eu/api/v2/logs","Err":{"Op":"dial","Net":"tcp","Source":null,"Addr":null,"Err":{"Err":"no such host","Name":"http-intake.logs.datadoghq.eu","Server":"","IsTimeout":false,"IsTemporary":false,"IsNotFound":true}}}
2024-08-13 14:32:29.951: Error occurred during sendPostRequestToDatadog in sendLogs:
2024-08-13 14:32:29.951: {"Op":"Post","URL":"https://http-intake.logs.datadoghq.eu/api/v2/logs","Err":{"Op":"dial","Net":"tcp","Source":null,"Addr":null,"Err":{"Err":"no such host","Name":"http-intake.logs.datadoghq.eu","Server":"","IsTimeout":false,"IsTemporary":false,"IsNotFound":true}}}
